// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqhnghycvrtliuvgbvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxaG5naHljdnJ0bGl1dmdidmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDE0NjMsImV4cCI6MjA3MzY3NzQ2M30.xA8Uye7KSyrOsEU11hZ0WaEm2bZHB_QZiXzmSMpYhmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});